[package]
name = "voxel-dream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
futures = "0.3.30"
noise = "0.9.0"
